// FILE: app/api/admin/approve/route.ts
// PURPOSE: Admin approve/reject pending registrations
// INDIA API: none — Supabase operations
// MOCK MODE: YES — returns success in demo

import { NextRequest, NextResponse } from 'next/server';
import { supabase } from '@/lib/supabase';

export const dynamic = 'force-dynamic';

export async function POST(req: NextRequest) {
  try {
    const { action, user_id, admin_user_id, rejection_note } = await req.json();

    if (action === 'approve') {
      await supabase.from('user_verifications').update({
        overall_status: 'VERIFIED',
        admin_approved: true,
        admin_approved_by: admin_user_id,
        admin_approved_at: new Date().toISOString(),
      }).eq('user_id', user_id);

      await supabase.from('pending_registrations').update({
        status: 'APPROVED',
        reviewed_by: admin_user_id,
        reviewed_at: new Date().toISOString(),
      }).eq('user_id', user_id);

      return NextResponse.json({ success: true, message: 'Registration approved' });
    }

    if (action === 'reject') {
      await supabase.from('user_verifications').update({
        overall_status: 'REJECTED',
        admin_rejection_note: rejection_note || 'Rejected by admin',
      }).eq('user_id', user_id);

      await supabase.from('pending_registrations').update({
        status: 'REJECTED',
        reviewed_by: admin_user_id,
        reviewed_at: new Date().toISOString(),
        review_note: rejection_note,
      }).eq('user_id', user_id);

      return NextResponse.json({ success: true, message: 'Registration rejected' });
    }

    if (action === 'generate_access_code') {
      const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
      let code = 'TS-AUD-';
      for (let i = 0; i < 6; i++) code += chars[Math.floor(Math.random() * chars.length)];

      await supabase.from('auditor_access_codes').insert({
        code,
        created_by: admin_user_id,
        expires_at: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
        note: 'Generated by NIC Admin',
      });

      return NextResponse.json({ success: true, code });
    }

    return NextResponse.json({ error: 'Unknown action' }, { status: 400 });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
