/**
 * CAG Auditor — Report Generator API
 * POST: Generate compliance report (HTML)
 * DUAL MODE: Supabase → Demo
 */
import { NextRequest, NextResponse } from 'next/server';

function generateTxHash() {
  return '0x' + Array.from({ length: 48 }, () => Math.floor(Math.random() * 16).toString(16)).join('');
}

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { report_type, scope, sections, auditor_name } = body;

    const reportId = `RPT-2025-${String(Math.floor(Math.random() * 9000) + 1000).padStart(4, '0')}`;
    const dateIST = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' });
    const reportHash = generateTxHash();

    // Build comprehensive report
    const tender = scope || {};
    const tId = tender.tender_id || 'TDR-MoH-2025-000003';
    const ministry = tender.ministry || 'MoH';
    const value = tender.value || 120;
    const riskScore = tender.risk_score || 94;
    const title = tender.title || 'AIIMS Delhi Medical Equipment';
    const auditor = auditor_name || 'CAG Auditor';

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>CAG Audit Report — ${reportId}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Georgia', 'Times New Roman', serif; margin: 40px 60px; color: #1a1a2e; line-height: 1.6; background: #fff; }
  .tricolor { height: 5px; background: linear-gradient(to right, #FF9933 33%, #FFFFFF 33%, #FFFFFF 66%, #138808 66%); margin-bottom: 24px; }
  .header { border-bottom: 3px solid #003f88; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { font-size: 20px; color: #003f88; letter-spacing: 1px; }
  .header h2 { font-size: 15px; color: #555; margin-top: 4px; }
  .header .meta { font-size: 12px; color: #666; margin-top: 8px; }
  .section { margin: 28px 0; page-break-inside: avoid; }
  .section h2 { font-size: 16px; color: #003f88; border-bottom: 1px solid #003f88; padding-bottom: 4px; margin-bottom: 12px; }
  .section h3 { font-size: 14px; color: #333; margin: 10px 0 5px; }
  .table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 13px; }
  .table th { background: #003f88; color: white; padding: 8px 10px; text-align: left; font-weight: 600; }
  .table td { padding: 7px 10px; border: 1px solid #ddd; }
  .table tr:nth-child(even) { background: #f8f9fa; }
  .risk-critical { color: #cc3300; font-weight: bold; }
  .risk-high { color: #e67300; font-weight: bold; }
  .risk-low { color: #2d7a4f; font-weight: bold; }
  .blockchain { font-family: 'Courier New', monospace; font-size: 11px; color: #555; word-break: break-all; }
  .certificate { border: 2px solid #003f88; padding: 20px; margin: 24px 0; background: #f8f9ff; }
  .certificate h2 { border: none; color: #003f88; }
  .footer { border-top: 2px solid #003f88; margin-top: 40px; padding-top: 12px; font-size: 10px; color: #888; text-align: center; }
  .confidential { color: #cc3300; font-weight: bold; font-size: 11px; text-transform: uppercase; letter-spacing: 2px; }
  ol li { margin: 5px 0; }
  @media print { .no-print { display: none; } body { margin: 20px 30px; } }
</style>
</head>
<body>
  <div class="tricolor"></div>
  <div class="header">
    <table width="100%"><tr>
      <td style="width:70%">
        <h1>COMPTROLLER AND AUDITOR GENERAL OF INDIA</h1>
        <h2>TenderShield AI — Procurement Audit Report</h2>
        <p class="confidential">CONFIDENTIAL — For Official Use Only</p>
      </td>
      <td style="text-align:right">
        <div class="meta">
          Report No: <strong>${reportId}</strong><br/>
          Date: ${dateIST}<br/>
          Generated by: ${auditor}<br/>
          Verified: Blockchain ✓
        </div>
      </td>
    </tr></table>
  </div>

  <div class="section">
    <h2>1. EXECUTIVE SUMMARY</h2>
    <p>This report presents the findings of an AI-assisted audit conducted on tender <strong>${tId}</strong> 
    titled "${title}" under the ${ministry} ministry. The TenderShield AI system detected multiple 
    irregularities with a composite risk score of <span class="${riskScore > 70 ? 'risk-critical' : 'risk-high'}">${riskScore}/100</span>.</p>
    <table class="table">
      <tr><td style="width:35%"><strong>Tender Reference</strong></td><td>${tId}</td></tr>
      <tr><td><strong>Ministry</strong></td><td>${ministry}</td></tr>
      <tr><td><strong>Estimated Value</strong></td><td>₹${value} Crore</td></tr>
      <tr><td><strong>AI Risk Score</strong></td><td class="risk-critical">${riskScore}/100 — ${riskScore > 70 ? 'CRITICAL' : riskScore > 40 ? 'HIGH' : 'MEDIUM'}</td></tr>
      <tr><td><strong>Audit Date</strong></td><td>${dateIST}</td></tr>
      <tr><td><strong>Recommended Action</strong></td><td>Keep frozen pending full investigation</td></tr>
    </table>
  </div>

  <div class="section">
    <h2>2. AI FRAUD ANALYSIS</h2>
    <h3>2.1. Shell Company Detection</h3>
    <p><strong>Evidence:</strong> Two bidding companies (BioMed Corp and Pharma Plus) share PAN ABCDE1234F and registered address "45 Nehru Place, New Delhi". Both incorporated within 45 days of each other.</p>
    <p><strong>Confidence:</strong> 92%</p>
    <p><strong>Plain English:</strong> These are likely the same entity submitting multiple bids to create an illusion of competition.</p>
    
    <h3>2.2. Bid Rigging / Timing Collusion</h3>
    <p><strong>Evidence:</strong> Three bids submitted within a 90-second window. Coefficient of variation = 2.1% (normal: 15-30%). All amounts within 0.25% of each other.</p>
    <p><strong>Confidence:</strong> 89%</p>
    <p><strong>Plain English:</strong> Bidders appear to have coordinated their submissions to arrive within seconds of each other with nearly identical amounts.</p>

    <h3>2.3. Benford's Law Violation</h3>
    <p><strong>Evidence:</strong> Chi-squared statistic = 14.2 (threshold: 15.5). Borderline violation detected in first-digit distribution of bid amounts.</p>
    <p><strong>Confidence:</strong> 61%</p>
    <p><strong>Plain English:</strong> The distribution of leading digits in financial figures shows artificial patterns inconsistent with natural data.</p>
  </div>

  <div class="section">
    <h2>3. BIDDER ANALYSIS</h2>
    <table class="table">
      <tr>
        <th>Company</th><th>GSTIN</th><th>Age</th><th>Bid (₹ Cr)</th><th>Trust Score</th><th>Flags</th>
      </tr>
      <tr>
        <td>BioMed Corp India</td>
        <td class="blockchain">07ABCDE1234F1Z5</td>
        <td>3 months</td>
        <td>119.8</td>
        <td>22/100</td>
        <td class="risk-critical">SHELL, SHARED_PAN</td>
      </tr>
      <tr>
        <td>Pharma Plus Equipment</td>
        <td class="blockchain">07ABCDE1234F2Z4</td>
        <td>2 months</td>
        <td>120.1</td>
        <td>18/100</td>
        <td class="risk-critical">SHELL, SHARED_PAN, TIMING</td>
      </tr>
      <tr>
        <td>MediCare India Pvt Ltd</td>
        <td class="blockchain">09FGHIJ5678K1Z2</td>
        <td>6 years</td>
        <td>115.5</td>
        <td>78/100</td>
        <td class="risk-low">NONE</td>
      </tr>
    </table>
  </div>

  <div class="section">
    <h2>4. BLOCKCHAIN EVIDENCE</h2>
    <table class="table">
      <tr><th>Event</th><th>Transaction Hash</th><th>Block</th><th>Time (IST)</th></tr>
      <tr>
        <td>Tender Published</td>
        <td class="blockchain">0x1d4e3f6a9b2c5e8f1a4d7c0b3e6a9f2c5b8e1d4a7f3c6</td>
        <td>#1342</td>
        <td>15 Mar 2025, 14:22 IST</td>
      </tr>
      <tr>
        <td>Bid Committed (BioMed)</td>
        <td class="blockchain">0x4f7a3b2c1d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2</td>
        <td>#1358</td>
        <td>15 Mar 2025, 16:58 IST</td>
      </tr>
      <tr>
        <td>Bid Committed (Pharma Plus)</td>
        <td class="blockchain">0x9c2e7f1a5b3d8e4c2a6f9b1d4e7c0a3f6b9e8d1c4a7f2</td>
        <td>#1359</td>
        <td>15 Mar 2025, 16:59 IST</td>
      </tr>
      <tr>
        <td>AI Auto-Freeze</td>
        <td class="blockchain">0x2e5c8b1d4a7f3c9e1b5d8a2f4e7c0b3d6a9e2c5b8f1d4a7</td>
        <td>#1360</td>
        <td>15 Mar 2025, 17:00 IST</td>
      </tr>
    </table>
    <p><em>All transactions verified on Hyperledger Fabric (Channel: tendershield-channel, Chaincode: tendercc v1.0).</em></p>
  </div>

  <div class="section">
    <h2>5. RECOMMENDED ACTIONS</h2>
    <ol>
      <li>Keep tender <strong>frozen</strong> pending full investigation</li>
      <li>Issue <strong>show-cause notice</strong> to BioMed Corp and Pharma Plus</li>
      <li>Investigate shared director (PAN: <span class="blockchain">ABCDE1234F</span>)</li>
      <li>Consider referral to <strong>Central Vigilance Commission</strong></li>
      <li>Review all 12 tenders created by officer Rajesh Kumar Sharma</li>
      <li>Preserve all blockchain evidence for potential FIR</li>
    </ol>
  </div>

  <div class="certificate">
    <h2>SECTION 65B CERTIFICATE</h2>
    <p style="margin:8px 0"><em>Under Section 65B(4) of the Indian Evidence Act, 1872</em></p>
    <p style="margin:8px 0">I, <strong>${auditor}</strong>, designated Competent Authority for TenderShield, 
    hereby certify that the electronic records contained in this report are true and accurate copies 
    of data maintained in the ordinary course of TenderShield operations on NIC (National Informatics Centre) infrastructure.</p>
    <p style="margin:8px 0">The computer systems generating these records were operating properly at all material times. 
    All blockchain transactions referenced herein are immutable and independently verifiable.</p>
    <table class="table" style="margin-top:12px">
      <tr><td><strong>Digital Signature</strong></td><td class="blockchain">${reportHash}</td></tr>
      <tr><td><strong>Report ID</strong></td><td>${reportId}</td></tr>
      <tr><td><strong>Date & Time</strong></td><td>${dateIST}</td></tr>
      <tr><td><strong>Platform</strong></td><td>TenderShield v1.0 — NIC Infrastructure</td></tr>
    </table>
  </div>

  <div class="footer">
    Generated by TenderShield AI | Blockchain verified | Report ID: ${reportId} | 
    Comptroller and Auditor General of India | <span class="confidential">CONFIDENTIAL</span>
  </div>
</body>
</html>`;

    return new NextResponse(html, {
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    });
  } catch (e: unknown) {
    return NextResponse.json({ error: (e instanceof Error ? e.message : String(e)) }, { status: 500 });
  }
}
